name: Update

on:
  schedule:
  - cron: 0 15 * * 0
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Get date
      run: |
        echo "DATE=$(date +%y%m%d)" >> $GITHUB_ENV
    - name: Run a multi-line script
      run: |
        git config user.name "eggplants"
        git config user.email "${{ secrets.MAIL }}"
        git remote set-url origin https://eggplants:${{ secrets.GITHUB_PASS }}@github.com/eggplants/nijisanji-v23d-status
        git branch
        git checkout master
        git branch
        chmod +x ./getinfo.sh
        ./getinfo.sh
        git add .
        git commit -m "update: ${{ env.DATE }}"
        git push origin master
